package bookstore.states;

public enum StoreStateEnum {
  LOGIN_SCREEN,
  ADMIN_START_SCREEN,
  ADMIN_BOOKS_SCREEN,
  ADMIN_CUSTOMERS_SCREEN,
  CUSTOMER_START_SCREEN,
  CUSTOMER_COST_SCREEN,
  UNDEFINED
}
